---
- name: Create dev user
  user:
      name: dev
      shell: /bin/bash
      group: admin
      state: present
      password: "{{ dev_user_password }}"

- name: Add ssh keys from github
  authorized_key:
      user: dev
      state: present
      key: "https://github.com/{{ github_user }}.keys"

- name: Add dev user to sudoers
  command: "usermod -aG sudo dev"
